website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: about/cv.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Journal"
        href: journal/index.qmd

