project:
  type: website
  
website:
  navbar:
    title: 'Fengtong(Farah) Du'
    background: '#efbbfa'
    search: true
    right:
      - text: "about me"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Journal"
        href: journal/index.qmd
      - text: "Publications"
        href: Publications/index.qmd

