project:
  type: website
  resources: 
    - google17802e267df74706.html
    - sitemap.xml
  
website:
  site-url: https://dufengtong.github.io
  search: true
  title: " Du Fengtong"
  description: "PhD student in computational neuroscience | Personal website"
  open-graph: true
  twitter-card: true
  navbar:
    title: 'Du Fengtong(Farah)'
    background: '#E0E0E0'
    search: true
    right:
      - text: "About me"
        href: index.qmd
      - text: "Project"
        href: projects/index.qmd
      - text: "Publication"
        href: publications/index.qmd
      - text: "Academic Activity"
        href: academia/index.qmd
      - text: "Blog"
        href: journals/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
