project:
  type: website
  resources: 
    - google17802e267df74706.html
  
website:
  site-url: https://dufengtong.github.io
  search: true
  title: "Fengtong Du"
  description: "PhD student in computational neuroscience | Personal website"
  open-graph: true
  twitter-card: true
  navbar:
    title: 'Fengtong(Farah) Du'
    background: '#efbbfa'
    search: true
    right:
      - text: "about me"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Academic Activities"
        href: academia/index.qmd
      - text: "Journal"
        href: journals/index.qmd

