---
title: "Du Fengtong (Farah)"
subtitle: "Neuroscience + AI"
format: html
execute: 
  enabled: false
listing: 
  contents: 
  - 'projects/posts/bullet.qmd'
  - 'projects/posts/minimodel.qmd'
  sort: 'date desc'
---

Hi! I’m Fengtong(Farah) Du , a PhD student in the [Janelia-JHU Joint Neuroscience Graduate Program](https://www.janelia.org/you-janelia/students-postdocs/joint-graduate-program), advised by Dr. Carsen Stringer. My work bridges computational modeling and systems neuroscience, with a focus on understanding how sensory information is represented in the brain and the unsupervised learning in the brain, how the brain learn from the outside world without obvious reinforcement signals.

I'm particularly interested in the intersection of artificial intelligence and neuroscience, especially how insights from the brain can inspire better algorithms, and how models can help us make sense of complex neural systems.

Outside the lab, I enjoy Chinese philosophy, Russian literature, and music. I spend time reflecting, writing, and practicing calligraphy. I also love occasional spontaneous adventure close to home.

## Poster and talks



cosyne 2021: Invariant texture recognition in mouse visual cortex


## Teaching Activities

**2025 — [Cajal NeuroAI Summer School](https://cajal-training.org/on-site/neuro-ai/)** — *Teaching Assistant*  
- Designed and delivered [tutorials](https://github.com/MouseLand/course-materials/tree/main/visual_models) on computational neuroscience and deep learning.  
- Mentored students on projects involving foundation models and unsupervised learning using JEPA.

**2023 — Probabilistic Machine Learning** — *Teaching Assistant*  
- Organized and assisted in teaching the course for neuroscience students at Janelia.  
- Based on the *[Probabilistic Machine Learning](https://probml.github.io/pml-book/book1.html)* book.

**2021 — [Neuromatch Academy](https://compneuro.neuromatch.io/tutorials/intro.html)** — *Teaching Assistant*  
- course TA of Neuromatch computational neuroscience course.

**2020 — [Neuromatch Academy](https://compneuro.neuromatch.io/tutorials/intro.html)** — *Teaching Assistant*  
- course TA of Neuromatch computational neuroscience course.


## Projects

